import Head from 'next/head'
import UrlForm from '../components/UrlFrom'
import UrlList from '../components/UrlList'
import { useEffect, useState } from 'react'
import axios from 'axios';

export default function Home() {

	const [urls, setUrls] = useState<{ id: number; description: string; originalUrl: string; shortUrl: string }[]>([]);

	useEffect(() => {
		const fetchUrls = async () => {
			try {
				const response = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/urls`);
				setUrls(response.data);
			} catch (error) {
				console.log(error);
			}
		};

		fetchUrls();
	}, []);

	return (
		<div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
			<Head>
				<title>Url Shortener App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Url Shortener</h1>
				<UrlForm setUrls={setUrls} />
				<UrlList urls={urls} setUrls={setUrls} />
			</main>
		</div>
	)
}
